# Generated by Django 4.0.5 on 2022-07-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('P', 'premium'), ('D', 'deluxe'), ('B', 'basic'), ('Q', 'Queen'), ('Q', 'King')], max_length=1),
        ),
    ]
