# Generated by Django 4.0.5 on 2022-07-02 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_alter_room_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('premium', 'P'), ('deluxe', 'D'), ('basic', 'B'), ('Queen', 'Q'), ('King', 'Q')], max_length=70),
        ),
    ]
