# Generated by Django 4.0.5 on 2022-07-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_alter_room_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('PRE', 'premium'), ('DEL', 'deluxe'), ('BAS', 'basic'), ('QUE', 'Queen'), ('QIN', 'King')], max_length=3),
        ),
    ]
